---
  name: CI
  
  on: 
    pull_request:
  
  permissions:
    contents: read  # Required for checking out the repository
    pull-requests: write  # Required for posting comments
  
  jobs:
    alex:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: reviewdog/action-alex@v1
          with:
            reporter: github-pr-review
  
    markdown:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: reviewdog/action-markdownlint@v0
          with:
            level: warning
            reporter: github-pr-review
  
    misspell:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: reviewdog/action-misspell@v1
          with:
            level: warning
            reporter: github-pr-review
  
    secret:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: reviewdog/action-misspell@v1
          with:
            level: warning
            reporter: github-pr-review
  
    terraform:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.7.4
  
        - run: terraform fmt -check -diff -recursive
  
    yamllint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: reviewdog/action-yamllint@v1
          with:
            reporter: github-pr-review
