---
  name: Plan Terraform
  
  on:
    pull_request:
  
  permissions:
    contents: read # Required for checking out the repository
    id-token: write # Required for OIDC authentication
    pull-requests: write # Required for posting comments
  
  jobs:
    terraform:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - id: changed-files
          uses: tj-actions/changed-files@v42
          with:
            # Note: .github should trigger the CI as to test the CI for Terraform
            files: |
              .github/workflows/**.yml
              **.tf
  
        - name: Run Terraform Plan
          if: steps.changed-files.outputs.any_changed == 'true'
          uses: ./.github/actions/terraform
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TF_IN_AUTOMATION: true
          with:
            aws-region: ap-northeast-1
            terraform-command: plan
            pd-token: ${{ secrets.PD_TOKEN }}
